AWSTemplateFormatVersion: 2010-09-09
Resources:
  DevCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: DevApp

  ChattingTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: ChattingTaskDev
          Essential: true
          Image: 022129665671.dkr.ecr.ap-northeast-2.amazonaws.com/leporem-art-socket
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/chatting-task-dev
              awslogs-region: ap-northeast-2
              awslogs-stream-prefix: ecs
          Environment:
            - Name: ENV
              Value: dev
      ExecutionRoleArn: arn:aws:iam::022129665671:role/ecsTaskExecutionRole
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        CpuArchitecture: ARM64
      NetworkMode: awsvpc
      Cpu: '256'
      Memory: '512'

  SwaggerTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: SwaggerTask
          Essential: true
          Image: swaggerapi/swagger-ui:v5.4.2
          PortMappings:
            - ContainerPort: 8080
              HostPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/swagger
              awslogs-region: ap-northeast-2
              awslogs-stream-prefix: ecs
          Environment:
            - Name: SWAGGER_JSON_URL
              Value: https://leporem-art-media-dev.s3.ap-northeast-2.amazonaws.com/swagger.yaml
      ExecutionRoleArn: arn:aws:iam::022129665671:role/ecsTaskExecutionRole
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: '256'
      Memory: '512'

  ChattingService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: chatting-service
      Cluster: !Ref DevCluster
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - sg-0cb0dd5e30baec000
          Subnets:
            - subnet-035df05ef63fc1027
            - subnet-0bdae204e69666160

  SwaggerService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: swagger-service
      Cluster: !Ref DevCluster
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - sg-0cb0dd5e30baec000
          Subnets:
            - subnet-035df05ef63fc1027
            - subnet-0bdae204e69666160
      TaskDefinition: !Ref SwaggerTaskDefinition